namespace FantasyEuroleague.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatePlayers : DbMigration
    {
       
        public override void Up()
        {
            //Sql(@"
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Bogdan', 'Radosavljevic', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Johannes', 'Thiemann', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jonas', 'Mattisseck', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kenneth', 'Ogbe', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kresimir', 'Nikic', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Croatia', 'HRV')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Landry', 'Nnoko', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Cameroon', 'CMR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Lorenz', 'Brenneke', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Luke', 'Sikma', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Makai', 'Mason', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Malte', 'Delow', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Marcus', 'Eriksson', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Sweden', 'SWE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Martin', 'Hermannsson', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Iceland', 'ISL')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Niels', 'Giffey', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Peyton', 'Siva', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Rokas', 'Giedraitis', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tim', 'Schneider', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tyler', 'Cavanaugh', 1, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Adrien', 'Moerman', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vasilije', 'Micic', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Krunoslav', 'Simon', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Croatia', 'HRV')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('James', 'Anderson', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tibor', 'Pleiss', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Dogus', 'Balbay', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Bryant', 'Dunston', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Shane', 'Larkin', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Rodrigue', 'Beaubois', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Brock', 'Motum', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Australia', 'AUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Bugrahan', 'Tuncer', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Metecan', 'Birsen', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Ireland', 'IRL')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Sertac', 'Sanli', 2, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Simone', 'Fontecchio', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Christian', 'Burns', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jeff', 'Brooks', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Andrea', 'Cinciarini', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Amedeo', 'Della Valle', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Mindaugas', 'Kuzminskas', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vladimir', 'Micov', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Mike', 'James', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Curtis', 'Jerrells', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kaleb', 'Tarczewski', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Dairis', 'Bertans', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Latvia', 'LVA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nemanja', 'Nedovic', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('James', 'Nunnally', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alen', 'Omic', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Slovenia', 'SVN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Arturas', 'Gudaitis', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Riccardo', 'Musumeci', 3, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kyle', 'Hines', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Othello', 'Hunter', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alec', 'Peters', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Will', 'Clyburn', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Sergio', 'Rodriguez', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Daniel', 'Hackett', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nando', 'De Colo', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nikita', 'Kurbanov', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Cory', 'Higgins', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Joel', 'Bolomboy', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Semen', 'Antonov', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Andrey', 'Vorontsevich', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ivan', 'Ukhov', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Mikhail', 'Kulagin', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Andrei', 'Lopatin', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alexander', 'Khomenko', 5, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kevin', 'Pangos', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Slovenia', 'SVN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Victor', 'Claver', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Pierre', 'Oriola', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Thomas', 'Heurtel', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Chris', 'Singleton', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kyle', 'Kuric', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Slovakia', 'SVK')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Pau', 'Ribas', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ante', 'Tomic', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Croatia', 'HRV')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Adam', 'Hanga', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Hungary', 'HUN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jaka', 'Blazic', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Slovenia', 'SVN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kevin', 'Seraphin', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Rolands', 'Smits', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Latvia', 'LVA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Artem', 'Pustovyi', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Ukraine', 'UKR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Aleix', 'Font', 6, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Danilo', 'Barthel', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nihad', 'Dedovic', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Petteri', 'Koponen', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Finland', 'FIN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nemanja', 'Dangubic', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vladimir', 'Lucic', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Derrick', 'Williams', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Maodo', 'Lo', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Leon', 'Radosevic', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Stefan', 'Jovic', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Braydon', 'Hobbs', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Devin', 'Booker', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Robin', 'Amaize', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alex', 'King', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Germany', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Marvin', 'Ogunsipe', 7, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Austria', 'AUT')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nicolo', 'Melli', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Marko', 'Guduric', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nikola', 'Kalinic', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Luigi', 'Datome', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Bobby Muhammed', 'Dixon Ali', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kostas', 'Sloukas', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jan', 'Vesely', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Czechia', 'CZE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Melih', 'Mahmutoglu', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ahmet', 'Duverioglu', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Erick', 'Green', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Joffrey', 'Lauvergne', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Sinan', 'Guler', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tarik', 'Biberovic', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tyler', 'Ennis', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Canada', 'CAN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Egehan', 'Arna', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ergi', 'Tirpanci', 8, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Turkey', 'TUR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tony', 'Crocker', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Malcolm', 'Thomas', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Charles', 'Jenkins', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jordan', 'Mickey', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Stefan', 'Markovic', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Sergei', 'Monia', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Andrey', 'Zubkov', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Dee', 'Bost', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Bulgaria', 'BGR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Egor', 'Vyaltsev', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vyacheslav', 'Zaytsev', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alexey', 'Shved', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Anthony', 'Gill', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Petr', 'Gubanov', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Garlon', 'Green', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Andrew', 'Harrison', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Timofey', 'Yakushin', 9, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vincent', 'Poirier', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ilimane', 'Diop', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Shavon', 'Shields', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Denmark', 'DNK')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Johannes', 'Voigtmann', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Germanu', 'GER')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Darrun', 'Hilliard', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Luca', 'Vildoza', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Marcelinho', 'Huertas', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tornike', 'Shengelia', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Bulgaria', 'BGR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Matt', 'Janning', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Georgia', 'GEO')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Patricio', 'Garino', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jalen', 'Jones', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jayson', 'Granger', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Italy', 'ITA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Miguel', 'Gonzalez', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tadas', 'Sedekerskis', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ajdin', 'Penava', 10, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Bosnia and Herzegovina', 'BIH')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Angelo', 'Caloiaro', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Johnny', 'O Bryant', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Alex', 'Tyus', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Yovel', 'Zoosman', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Scottie', 'Wilbekin', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Michael', 'Roll', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('John', 'DiBartolomeo', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Tarik', 'Black', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Deandre', 'Kane', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jake', 'Cohen', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kendrick', 'Ray', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Jeremy', 'Pargo', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Deni', 'Avdija', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nimrod', 'Levi', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Ramon', 'Sessions', 12, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vangelis', 'Mantzaris', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Aleksandar', 'Vezenkov', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Zach', 'LeDay', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nikola', 'Milutinov', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Nigel', 'Williams-Goss', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Kostas', 'Papanikolaou', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Giorgos', 'Printezis', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Giorgos', 'Bogris', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Axel', 'Toupane', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vassilis', 'Spanoulis', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Janis', 'Timma', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Latvia', 'LVA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Janis', 'Strelnieks', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Latvia', 'LVA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Dimitris', 'Agravanis', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Briante', 'Weber', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Vassilis', 'Toliopoulos', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Greece', 'GRE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Will', 'Cherry', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('Matt', 'Lojeski', 13, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('CAUSEUR', 'FABIEN', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('RANDOLPH', 'ANTHONY', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('FERNANDEZ', 'RUDY', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('CAMPAZZO', 'FACUNDO', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Argentina', 'ARG')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('REYES', 'FELIPE', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('AYON', 'GUSTAVO', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Mexico', 'MEX')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('YUSTA', 'SANTI', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('PANTZAR', 'MELWIN', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Sweden', 'SWE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('CARROLL', 'JAYCEE', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('TAVARES', 'WALTER', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Cabo Verde', 'CPV')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('LLULL', 'SERGIO', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DECK', 'GABRIEL', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Argentina', 'ARG')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('PREPELIC', 'KLEMEN', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('KUZMIC', 'OGNJEN', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Slovenia', 'SVN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('THOMPKINS', 'TREY', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Serbia', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('TAYLOR', 'JEFFERY', 15, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('GARCIA', 'SERGI', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('ABALDE', 'ALBERTO', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('LABEYRIE', 'LOUIS', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DIOT', 'ANTOINE', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('VAN ROSSOM', 'SAM', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Belgium', 'BEL')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('THOMAS', 'WILL', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('TOBEY', 'MIKE', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DUBLJEVIC', 'BOJAN', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Montenegro', 'MNE')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('VIVES', 'GUILLEM', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('MARTINEZ', 'RAFA', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('SAN EMETERIO', 'FERNANDO', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('THOMAS', 'MATT', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('SASTRE', 'JOAN', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DOORNEKAMP', 'AARON', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Netherlands', 'NLD')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('GALARZA', 'JON', 16, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Spain', 'ESP')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DAVIES', 'BRANDON', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Uganda', 'UGA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('THOMPSON', 'DEON', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('WOLTERS', 'NATE', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('WALKUP', 'THOMAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('WESTERMANN', 'LEO', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'France', 'FRA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('ULECKAS', 'LUKAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('VENSKUS', 'ERIKAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('JANKUNAS', 'PAULIUS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('BIRUTIS', 'LAURYNAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('MILAKNIS', 'ARTURAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('WHITE', 'AARON', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('JOKUBAITIS', 'ROKAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('GRIGONIS', 'MARIUS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('KAVALIAUSKAS', 'ANTANAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('ULANOVAS', 'EDGARAS', 17, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Lithuania', 'LTU')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('ARMAND', 'SEAN', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('REYNOLDS', 'JALEN', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('KARASEV', 'SERGEY', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('MEKEL', 'GAL', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Israel', 'ISR')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('DESIATNIKOV', 'ANDREI', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('MILLER-MCINTYRE', 'CODI', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('BALASHOV', 'SERGEI', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('PUSHKOV', 'ANTON', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 3, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('TRUSHKIN', 'VLADISLAV', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('VORONOV', 'EVGENY', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('SIMONOVIC', 'MARKO', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'SERBIA', 'SRB')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('PANIN', 'VADIM', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('UTHOFF', 'JARROD', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'USA', 'USA')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('SCRUBB', 'PHILIP', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 1, 'Canada', 'CAN')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('VALIEV', 'EVGENY', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //    INSERT INTO Players (Firstname, Lastname, TEAMID, FantasyPoints, Price) VALUES ('USOLTSEV', 'ILIA', 18, 100.00, 20.00) 
            //    INSERT INTO PROFILES (PlayerID, Position, COUNTRY, Country3Code) VALUES (SCOPE_IDENTITY(), 2, 'Russian Federation', 'RUS')
            //     ");
        }

        public override void Down()
        {
            //Sql(@"
            //        DELETE FROM PROFILES
            //        WHERE PlayerID BETWEEN 50 AND 280
            //        DELETE FROM Players
            //        WHERE ID BETWEEN 50 AND 280
            //        DBCC CHECKIDENT ('Players',RESEED, 49)
            //");
        }
    }
}
      